#release configuration
#Sat Apr 25 14:54:43 EEST 2026
completedPhase=check-poms
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
projectVersionPolicyId=default
pushChanges=true
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
scm.id=github
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:https\://github.com/voznyukpavel/maven-guru-classes.git
